syntax = "proto3";

option csharp_namespace = "Log_Server.Grpc";

package log_service;

service LogService {
  rpc LogEntry(LogRequest) returns (LogResponse);
  rpc LogBatch(LogBatchRequest) returns (LogResponse);
  rpc GetLogs(GetLogsRequest) returns (GetLogsResponse);
}

message LogRequest {
  string id = 1;
  int64 timestamp = 2;
  string service_name = 3;
  int32 level = 4;
  string category = 5;
  string message = 6;
  string user_id = 7;
  string session_id = 8;
  map<string, string> data = 9;
  string trace_id = 10;
}

message LogBatchRequest {
  repeated LogRequest logs = 1;
}

message LogResponse {
  bool success = 1;
  string message = 2;
}

message GetLogsRequest {
  int64 from_timestamp = 1;
  int64 to_timestamp = 2;
  string service_filter = 3;
  int32 level_filter = 4;
}

message GetLogsResponse {
  repeated LogRequest logs = 1;
  int32 total_count = 2;
}